name: Quality assurance

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Codestyle check (ESLint)
      run: npm run lint

    - name: Tests
      run: npm run e2e
